#!/usr/bin/env ruby
$: << File.expand_path('../../lib', __FILE__)
require 'dat'
include Dat

def relative_unreachable(infile, outfile)
  dict = Dict.new(:file => infile)
  logic = Pure::Logic.new dict

  dict.each do |k,v|
    results = logic.perturb(k, :transpose => true, :min_size => 2)
    if v.relatives.union(results).difference(v.relatives).empty?
      dict.delete(v)
    end
  end

  outfile.puts dict
end


relative_unreachable File.open('../data/nounreachable.txt'), File.open('../data/norelativereachable.txt', 'w')
