#!/usr/bin/env ruby
$: << File.expand_path('../../lib', __FILE__)
require 'dat'
include Dat

def relative_unreachable(infile, outfile)
  dict = Dict.new(:file => infile)
  logic = Pure::Logic.new dict

  dict.each do |k,v|
    neighbors = logic.perturb(k, :transpose => true, :min_size => 2)

    n2 = Set.new
    neighbors.each do |n|
      logic.perturb(n.get, :transpose => true, :min_size => 2).map { |e| n2.add(e) }
    end

    neighbors << v
    if n2.difference(neighbors).empty?
      neighbors.each do |n|
        # TODO worry that removing stuff makes other things no longer good?
        puts n
        dict.delete(n)
      end
    end
  end

  outfile.puts dict
end


relative_unreachable File.open('../data/norelativereachable.txt'), File.open('../data/nocircles.txt', 'w')
