#!/usr/bin/env ruby
$: << File.expand_path('../../lib', __FILE__)
require 'dat'
include Dat

def unreachable(infile, outfile)
  dict = Dict.new(:file => infile)
  logic = Pure::Logic.new dict

  dict.each do |k,v|
    results = logic.perturb(k, :transpose => true, :min_size => 2)
    if results.empty?
      dict.delete(v)
    end
  end

  outfile.puts dict
end

unreachable File.open('../data/all.txt'), File.open('../data/nounreachable.txt', 'w')
