#!/usr/bin/env ruby
$: << File.expand_path('../../lib', __FILE__)
require 'dat'
include Dat
require 'set'

d1 = Dict.new(:file => File.open(ARGV[0]))
d2 = Dict.new(:file => File.open(ARGV[1]))

s1 = Set.new
d1.each do |k,v|
  s1.add(k)
end

s2 = Set.new
d2.each do |k,v|
  s2.add(k)
end

p s1.difference(s2)
