#!/usr/bin/env ruby
$: << File.expand_path('../../lib', __FILE__)
require 'dat'
require 'curb'
require 'nokogiri'

('A'..'Z').each do |char|
  File.open("words/list-#{char}", 'w') do |f|
    c = Curl::Easy.http_post("http://www.hasbro.com/scrabble/en_US/search.cfm", "dictWord=#{char.downcase}")
    c.perform
    doc = Nokogiri::HTML(c.body_str)
    f.puts doc.css('#dictionary').to_s
  end
end
