#!/usr/bin/env ruby
$: << File.expand_path('../../lib', __FILE__)
require 'dat'
include Dat

## Insert code to run
d = Dict.new
p Logic.perturb('WALKED', d) # fails for c`
p Pure::Logic.perturb('WALKED', d) # fails for c`
=begin
r = (Logic.perturb 'DAT', d)
p r.size
p r
p (Logic.perturb 'DAT', d, :min_size => 3, :add => false).size


#l = Logic.path(d, Word.new('dat'), Word.new('lame'), nil, [], :min_size => 3, :max_depth => 20)
#k = Logic.path(d, Word.new('lame'), Word.new('labia'), nil, [], :min_size => 3, :max_depth => 20)

#puts "RESULT: "
#p [l, k]

#p Logic.perturb 'sis', d, :min_size => 3
p Logic.leven('kitten', 'sitting') # => 3
p Logic.leven('xyzzy', 'hellosmal') # => 9

p Logic.damlev 'CA', 'ABC' # => 2
p Logic.damlev 'TEUSDAY', 'TUESDAY' # => 1
p Logic.damlev 'TEUSDAY', 'THRUSDAY' # => 2
p Logic.damlev 'TUESDAY', 'SOMETHING' # => 8
=begin
p Logic.jaro_winkler 'MARTHA', 'MARHTA' # => 0.961
p Logic.jaro_winkler 'DWAYNE', 'DUANE' # => 0.84
p Logic.jaro_winkler 'DIXON', 'DICKSONX' # => 0.813
p Logic.jaro_winkler 'DIXON', 'DIXON' # => 1.0
=end
