#!/usr/bin/env ruby
$: << File.expand_path('../../lib', __FILE__)
require 'dat'
include Dat

## Insert code to run
d = Dict.new

p Logic.perturb('AAHING', d)

#c = CDict.new
#c.add 'HELLO'
#c.add 'GOODBYE'
#c.include? 'HELLO'
=begin
d.each do |k,v|
  c.add k
end

c.delete 'AAH'
c.delete 'AAL'

d.each do |k, v|
 p c.include? k
end
=end
