#!/usr/bin/env ruby
$: << File.expand_path('../../lib', __FILE__)
require 'dat'
include Dat

## Insert code to run
#d = Dict.new

#p (Logic.perturb 'dat', d, :min_size => 3, :add => false).size

#l = Logic.path(d, Word.new('dat'), Word.new('lame'), nil, [], :min_size => 3, :max_depth => 20)
#k = Logic.path(d, Word.new('lame'), Word.new('labia'), nil, [], :min_size => 3, :max_depth => 20)

#puts "RESULT: "
#p [l, k]

#p Logic.perturb 'sis', d, :min_size => 3
#p Logic.levenshtein('kitten', 'sitting')
#p Logic.levenshtein('xyzzy', 'hellosmal')

p Logic.damerau_levenshtein 'ca', 'abc' # => 2
p Logic.damerau_levenshtein 'teusday', 'tuesday' # => 1
p Logic.damerau_levenshtein 'teusday', 'thursday' # => 2
p Logic.damerau_levenshtein 'tuesday', 'something' # => 8
